package domain

import (
	"time"

	"github.com/google/uuid"
)

// Alert represents an alert generated by the rule engine when a parsed
// event matches a detection rule.  It maps to the `alerts` PostgreSQL table.
//
// rule_name is denormalized: if the originating rule is later deleted, the
// alert record retains the human-readable rule name for historical context.
type Alert struct {
	ID             uuid.UUID     `json:"id"`
	RuleID         *uuid.UUID    `json:"rule_id,omitempty"`
	RuleName       string        `json:"rule_name"`
	EventID        *int64        `json:"event_id,omitempty"`
	LogSourceID    *uuid.UUID    `json:"log_source_id,omitempty"`
	Severity       SeverityLevel `json:"severity"`
	Title          string        `json:"title"`
	Description    *string       `json:"description,omitempty"`
	RawLine        *string       `json:"raw_line,omitempty"`
	TriggeredAt    time.Time     `json:"triggered_at"`
	Acknowledged   bool          `json:"acknowledged"`
	AcknowledgedAt *time.Time    `json:"acknowledged_at,omitempty"`
	DiscordSent    bool          `json:"discord_sent"`
}
