-- ============================================================
-- PUSINGBERAT SIEM — Migration 001: Tables & Triggers
-- Run order: This file MUST run before 002_add_indexes.sql
-- ============================================================

-- ============================================================
-- EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- provides gen_random_uuid()


-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE severity_level AS ENUM (
    'info',
    'low',
    'medium',
    'high',
    'critical'
);

CREATE TYPE log_source_status AS ENUM (
    'active',
    'inactive',
    'error'
);


-- ============================================================
-- TABLE: log_sources
-- Tracks registered log file paths and their watcher state.
-- ============================================================
CREATE TABLE log_sources (
    id          UUID                 PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255)         NOT NULL,
    file_path   TEXT                 NOT NULL UNIQUE,
    log_type    VARCHAR(64)          NOT NULL DEFAULT 'generic', -- 'syslog' | 'nginx' | 'generic'
    status      log_source_status    NOT NULL DEFAULT 'active',
    description TEXT,
    created_at  TIMESTAMPTZ          NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ          NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: events
-- Every parsed log line becomes one row here.
-- High-volume table — keep inserts lean, query via indexes.
-- ============================================================
CREATE TABLE events (
    id            BIGSERIAL    PRIMARY KEY,
    log_source_id UUID         NOT NULL REFERENCES log_sources(id) ON DELETE CASCADE,
    raw_line      TEXT         NOT NULL,
    message       TEXT,
    hostname      VARCHAR(255),
    process       VARCHAR(128),
    pid           INTEGER,
    log_level     VARCHAR(32),
    event_time    TIMESTAMPTZ  NOT NULL,                 -- timestamp parsed from the log line
    received_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),   -- timestamp of ingestion into DB
    extra         JSONB                                  -- arbitrary parser-extracted key/value pairs
);


-- ============================================================
-- TABLE: rules
-- YAML-based detection rules stored as text alongside metadata.
-- Enabled flag allows toggling without deletion.
-- ============================================================
CREATE TABLE rules (
    id           UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    name         VARCHAR(255)   NOT NULL UNIQUE,
    description  TEXT,
    yaml_content TEXT           NOT NULL,               -- raw YAML for live editing in the UI
    severity     severity_level NOT NULL DEFAULT 'medium',
    enabled      BOOLEAN        NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: alerts
-- Records generated by the rule engine when a rule fires.
-- rule_name is intentionally denormalized so historical alerts
-- survive future rule deletion (rule_id → ON DELETE SET NULL).
-- ============================================================
CREATE TABLE alerts (
    id              UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id         UUID           REFERENCES rules(id)       ON DELETE SET NULL,
    rule_name       VARCHAR(255)   NOT NULL,                  -- denormalized: survives rule deletion
    event_id        BIGINT         REFERENCES events(id)      ON DELETE SET NULL,
    log_source_id   UUID           REFERENCES log_sources(id) ON DELETE SET NULL,
    severity        severity_level NOT NULL,
    title           TEXT           NOT NULL,
    description     TEXT,
    raw_line        TEXT,
    triggered_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    acknowledged    BOOLEAN        NOT NULL DEFAULT false,
    acknowledged_at TIMESTAMPTZ,
    discord_sent    BOOLEAN        NOT NULL DEFAULT false
);


-- ============================================================
-- TRIGGER FUNCTION: set_updated_at
-- Automatically keeps updated_at current on every UPDATE.
-- Shared by both log_sources and rules tables.
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_sources_updated_at
    BEFORE UPDATE ON log_sources
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_rules_updated_at
    BEFORE UPDATE ON rules
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();