package repository

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/NCC-Oprec-FP-2026/PUSINGBERAT/internal/domain"
)

// AlertRepo provides CRUD operations for the alerts table.
type AlertRepo struct {
	pool *pgxpool.Pool
}

// NewAlertRepo creates a new AlertRepo backed by the given connection pool.
func NewAlertRepo(pool *pgxpool.Pool) *AlertRepo {
	return &AlertRepo{pool: pool}
}

// Create inserts a new Alert into the database. The ID and TriggeredAt
// columns are generated by PostgreSQL and scanned back into the struct.
func (r *AlertRepo) Create(ctx context.Context, a *domain.Alert) error {
	query := `
		INSERT INTO alerts (rule_id, rule_name, event_id, log_source_id, severity,
		                     title, description, raw_line, discord_sent)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
		RETURNING id, triggered_at`

	err := r.pool.QueryRow(ctx, query,
		a.RuleID,
		a.RuleName,
		a.EventID,
		a.LogSourceID,
		a.Severity,
		a.Title,
		a.Description,
		a.RawLine,
		a.DiscordSent,
	).Scan(&a.ID, &a.TriggeredAt)

	if err != nil {
		return fmt.Errorf("alertRepo.Create: %w", err)
	}
	return nil
}

// GetByID retrieves a single Alert by its UUID primary key.
func (r *AlertRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Alert, error) {
	query := `
		SELECT id, rule_id, rule_name, event_id, log_source_id, severity,
		       title, description, raw_line, triggered_at,
		       acknowledged, acknowledged_at, discord_sent
		FROM alerts
		WHERE id = $1`

	a := &domain.Alert{}
	err := r.pool.QueryRow(ctx, query, id).Scan(
		&a.ID,
		&a.RuleID,
		&a.RuleName,
		&a.EventID,
		&a.LogSourceID,
		&a.Severity,
		&a.Title,
		&a.Description,
		&a.RawLine,
		&a.TriggeredAt,
		&a.Acknowledged,
		&a.AcknowledgedAt,
		&a.DiscordSent,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("alertRepo.GetByID: %w", err)
	}
	return a, nil
}

// AlertListParams holds optional filter/pagination parameters for List.
type AlertListParams struct {
	Limit  int
	Offset int
}

// List retrieves alerts ordered by triggered_at descending with pagination.
func (r *AlertRepo) List(ctx context.Context, params AlertListParams) ([]domain.Alert, int64, error) {
	if params.Limit <= 0 {
		params.Limit = 50
	}
	if params.Limit > 200 {
		params.Limit = 200
	}

	var total int64
	countQuery := `SELECT COUNT(*) FROM alerts`
	if err := r.pool.QueryRow(ctx, countQuery).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("alertRepo.List count: %w", err)
	}

	query := `
		SELECT id, rule_id, rule_name, event_id, log_source_id, severity,
		       title, description, raw_line, triggered_at,
		       acknowledged, acknowledged_at, discord_sent
		FROM alerts
		ORDER BY triggered_at DESC
		LIMIT $1 OFFSET $2`

	rows, err := r.pool.Query(ctx, query, params.Limit, params.Offset)
	if err != nil {
		return nil, 0, fmt.Errorf("alertRepo.List: %w", err)
	}
	defer rows.Close()

	var alerts []domain.Alert
	for rows.Next() {
		var a domain.Alert
		if err := rows.Scan(
			&a.ID,
			&a.RuleID,
			&a.RuleName,
			&a.EventID,
			&a.LogSourceID,
			&a.Severity,
			&a.Title,
			&a.Description,
			&a.RawLine,
			&a.TriggeredAt,
			&a.Acknowledged,
			&a.AcknowledgedAt,
			&a.DiscordSent,
		); err != nil {
			return nil, 0, fmt.Errorf("alertRepo.List scan: %w", err)
		}
		alerts = append(alerts, a)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("alertRepo.List rows: %w", err)
	}
	return alerts, total, nil
}

// Acknowledge sets acknowledged = true and acknowledged_at = NOW() for the
// given alert. Returns the updated Alert so the handler can return it.
func (r *AlertRepo) Acknowledge(ctx context.Context, id uuid.UUID) (*domain.Alert, error) {
	query := `
		UPDATE alerts
		SET acknowledged = true, acknowledged_at = $2
		WHERE id = $1 AND acknowledged = false
		RETURNING id, rule_id, rule_name, event_id, log_source_id, severity,
		          title, description, raw_line, triggered_at,
		          acknowledged, acknowledged_at, discord_sent`

	a := &domain.Alert{}
	now := time.Now().UTC()
	err := r.pool.QueryRow(ctx, query, id, now).Scan(
		&a.ID,
		&a.RuleID,
		&a.RuleName,
		&a.EventID,
		&a.LogSourceID,
		&a.Severity,
		&a.Title,
		&a.Description,
		&a.RawLine,
		&a.TriggeredAt,
		&a.Acknowledged,
		&a.AcknowledgedAt,
		&a.DiscordSent,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("alertRepo.Acknowledge: %w", err)
	}
	return a, nil
}

// Delete removes an Alert by ID.
func (r *AlertRepo) Delete(ctx context.Context, id uuid.UUID) error {
	query := `DELETE FROM alerts WHERE id = $1`

	ct, err := r.pool.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("alertRepo.Delete: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return domain.ErrNotFound
	}
	return nil
}

// MarkDiscordSent updates the discord_sent flag to true for a given alert.
func (r *AlertRepo) MarkDiscordSent(ctx context.Context, id uuid.UUID) error {
	query := `UPDATE alerts SET discord_sent = true WHERE id = $1`

	ct, err := r.pool.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("alertRepo.MarkDiscordSent: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return domain.ErrNotFound
	}
	return nil
}
